wandb_version: 1

learning_rate:
  desc: null
  value: 0.0002
epochs:
  desc: null
  value: 3000
_wandb:
  desc: null
  value:
    python_version: 3.7.13
    cli_version: 0.17.2
    framework: huggingface
    huggingface_version: 4.30.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1722007328
    t:
      1:
      - 1
      - 11
      - 41
      - 49
      - 55
      2:
      - 1
      - 11
      - 41
      - 49
      - 55
      3:
      - 16
      - 23
      4: 3.7.13
      5: 0.17.2
      6: 4.30.2
      8:
      - 5
      13: linux-x86_64
